global using Journey.Application.Data.Interfaces;
global using Journey.Domain.Abstractions;
global using Journey.Domain.ValueObjects;
global using Journey.Infrastructure.Data;
global using Journey.Infrastructure.Outbox;
global using MediatR;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Newtonsoft.Json;
global using System.Reflection;
global using JourneyEntity = Journey.Domain.Models.Journey.Journey;

