global using BuildingBlocks.CQRS;
global using BuildingBlocks.Exceptions;
global using Journey.Application.Data;
global using Journey.Application.Dtos;
global using Journey.Application.Exceptions;
global using Journey.Application.Journeys.Commands.CreateOrder;
global using Journey.Domain.Events;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using JourneyEntity = Journey.Domain.Models.Journey;
