global using BuildingBlocks.CQRS;
global using BuildingBlocks.Exceptions;
global using Journey.Application.Data;
global using Journey.Application.Dtos;
global using Journey.Application.Exceptions;
global using Journey.Application.Journeys.Commands.CreateJourney;
global using Journey.Application.Journeys.Queries.GetJourney;
global using Journey.Domain.Events;
global using Mapster;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Serilog;
global using JourneyEntity = Journey.Domain.Models.Journey;
global using Microsoft.Extensions.Logging;
