services:
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: ApiGateway/Gateway.API
      dockerfile: Dockerfile
    ports:
       - "5000:5000"
       - "5001:5001"
    networks:
       - backend

  journey.api:
    image: ${DOCKER_REGISTRY-}journeyapi
    build:
      context: .
      dockerfile: Services/JourneyService/Journey.API/Dockerfile
    ports:
        - "5100:5100"
        - "5002:5002"
    networks: 
    - backend    
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver;Database=JourneyDb;User=sa;Password=Your_password123!;Encrypt=False;TrustServerCertificate=True;
    depends_on: 
     - sqlserver


  sqlserver:
       image: mcr.microsoft.com/mssql/server:2022-latest
       container_name: sqlserver
       ports:
         - "1433:1433"
       environment:
           MSSQL_SA_PASSWORD: "Your_password123!"
           ACCEPT_EULA: "Y"
       networks:
         - backend

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: Keycloak
      command: start-dev
      environment:
          - KC_HEALTH_ENABLED=true
          - KEYCLOAK_ADMIN=admin
          - KEYCLOAK_ADMIN_PASSWORD=admin
      volumes:
          - ./.containers/identity:/opt/keycloak/data
      ports:
       - 18080:8080

networks:
  backend:
    driver: bridge
